### ISSUE TITLE
Curious about switch from Alpine in v0.1.0 to CentOS in v0.1.1

### ISSUE THREAD

**Issue by cpick** [grapeshot/vault_exporter#14]
I was browsing through the project's history and noticed that the v0.1.0 Docker image was based on Alpine Linux, but for v0.1.1 that changed to CentOS.
I was curious about the reason why (as I frequently have to make this kind of base-image decision for my own projects).

Thanks for any thoughts and for writing and releasing this useful tool!

**Comment by jdbaldry** [comment]
Hi! 
Primarily the descision was motivated by the needs of the Grapeshot Systems team and much less driven by the project needs. Essentially, it boils down to a desire from the System Administrators to have a common container image and they like CentOS because it is the same as the physical servers they run. 

Hope the change isn't too inconvenient!

**Comment by cpick** [comment]
That's what I was thinking the case was.

It leaves the image a bit larger, but it's not inconvenient.  Thanks again.
